### ISSUE TITLE
[Bug] 点击恢复报错...

### ISSUE THREAD

**Issue by getcurl** [XayahSuSuSu/Android-DataBackup#68]
**Smartphone (please complete the following information):**
 - Device: [Redmi  k40]
 - OS: [MIUI13, Android12]
 - Version [Stable 13.0.6 ]

2023-01-30 16:31:10
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.xayah.databackup.util.Command$Companion$getMediaInfoRestoreMap$2.invokeSuspend(Command.kt:363)
	at com.xayah.databackup.util.Command$Companion$getMediaInfoRestoreMap$2.invoke(Unknown Source:8)
	at com.xayah.databackup.util.Command$Companion$getMediaInfoRestoreMap$2.invoke(Unknown Source:2)
	at com.xayah.databackup.util.Command$Companion$runOnIO$2.invokeSuspend(Command.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@37bf8b4, Dispatchers.Main.immediate]

**Comment by XayahSuSuSu** [comment]
确为未捕获异常，已在 https://github.com/XayahSuSuSu/Android-DataBackup/commit/ba293daf29812ef44a2513847a1c6d95901b74b1 中修复，但能否查看一下你的媒体备份目录，我怀疑你的备份目录结构可能有问题
